import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {getServerSession} from "next-auth";
import {authOptions} from "@/app/api/auth/[...nextauth]/auth";
import SessionProvider from "@/app/components/SessionProvider";
import LoginStatus from "@/app/components/LoginStatus";
import TapBar from "./TapBar";


const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({children,}: {
  children: React.ReactNode
}) {
  const sessionData = await getServerSession(authOptions)

  return (
    <html lang="en">
    <SessionProvider session={sessionData}>
      <body className={inter.className}>
      <div className="flex items-center bg-amber-100">
        <LoginStatus />
      </div>
      <TapBar />
      {children}
      </body>
    </SessionProvider>
    </html>
  )
}
