import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import LoginButton from "@/app/components/LoginButton";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div>
        <span> This is layout</span>
        <LoginButton></LoginButton>
      </div>
      {children}
      </body>
    </html>
  )
}
